name: Update README Dynamic Content

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README Stats
        uses: teoxoy/profile-readme-stats@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md

          git diff --cached --quiet || git commit -m "Update README dynamic content"

          git push
